### ISSUE TITLE
Ask for dark mode

### ISSUE THREAD

**Issue by liziwl** [meilisearch/vuepress-plugin-meilisearch#127]
need dark mode.

I use https://github.com/tolking/vuepress-theme-default-prefers-color-scheme to enable dark mode. But this plugin is not compatible with dark mode

**Comment by bidoubiwa** [comment]
Hello @liziwl 
This plugin uses https://github.com/meilisearch/docs-searchbar.js for the search result layout. Could you check there if there is a possible dark mode? In which case it shouln't be to hard to enable it here. 

If you have no time for it no problem! I will look for it but we'll have to wait a bit as I have not much time right now 😅

**Comment by liziwl** [comment]
> Hello @liziwl
> This plugin uses https://github.com/meilisearch/docs-searchbar.js for the search result layout. Could you check there if there is a possible dark mode? In which case it shouln't be to hard to enable it here.
> 
> If you have no time for it no problem! I will look for it but we'll have to wait a bit as I have not much time right now 😅

`docs-searchbar.js` doesn't seem to be able to adjust dark mode of the drop-down menu very well.
I haven't found the right CSS selector that changes the background color correctly.

At present, I use a temporary solution, but in this case, the dark colors are not very unified.

```css
@media (prefers-color-scheme: dark) {
    .search-box .dsb-dropdown-menu{
        filter: invert(1) hue-rotate(180deg);
    }
}
```

**Comment by liziwl** [comment]
thx，great job!
