### ISSUE TITLE
Remove use of `!important` in CSS

### ISSUE THREAD

**Issue by mdubus** [meilisearch/vuepress-plugin-meilisearch#172]
There are !important in CSS. This is a bad practice and it would be nice to remove them.
If so, we have to be careful that it might be breaking.

![Capture d’écran 2021-07-07 à 16 38 56](https://user-images.githubusercontent.com/30866152/124779268-edc65b00-df41-11eb-8ca1-8a3cbd8ae870.png)

**Comment by nandan-shah** [comment]
hey, can I work on this?

**Comment by bidoubiwa** [comment]
Sure good luck :) Be sure that the visual results are the same before and after.

**Comment by Smartmind12** [comment]
@mdubus @bidoubiwa Kindly review the PR ...Thanks!

**Comment by bidoubiwa** [comment]
Hey @Smartmind12 :) Thanks for contributing! No need to ping us on the issue, we receive the notification of the PR 😊 We will be reviewing it as soon as we can
