### ISSUE TITLE
add a fallback for vuepress default search

### ISSUE THREAD

**Issue by bestony** [meilisearch/vuepress-plugin-meilisearch#174]
**Description**
Sometimes Meilisearch server will down. then, the search bar will not worked.

maybe has a fallback options is better for user experience. 

**Basic example**
for sometimes my Meilisearch down. 

**Other**
nothing.

**Comment by bidoubiwa** [comment]
Hello! Thanks a lot for raising this suggestion. I'm not sure this is the purpose of this plugin. We would have to decide build for both cases and if your server does not answer we would have to decide after how many retry we fallback to the default search bar. Maybe this is more simple that I'm aware of, in which case maybe someone could help us out. 

In either case, I think this may be possible using a custom script inside your vuepress. You can check if your server is up and then if  it is not you do not use the plugin and it will fallback to the default plugin.

**Comment by bidoubiwa** [comment]
Since we aggreed on the conclusion, I close this issue 🔥
