### ISSUE TITLE
navigation failed when title is contain chinese

### ISSUE THREAD

**Issue by rmGFW** [meilisearch/vuepress-plugin-meilisearch#252]
<img width="1159" alt="image" src="https://user-images.githubusercontent.com/66858140/186441918-f9a87efe-f62c-49ec-9ff4-6525ef14ad86.png">

**Comment by bidoubiwa** [comment]
Hey @rmGFW could you provide the settings of the plugin from your config.js ?

**Comment by rmGFW** [comment]
> Hey @rmGFW could you provide the settings of the plugin from your config.js ?

```js
module.exports = {
  themeConfig: {
    editLinks: true,
    logo: '/logo.svg',
    sidebarDepth: 1,
    smoothScroll: true,
    nav: [
    ],
    sidebar: {
    },
  },
  plugins: [
    [
      'check-md',
      {
        pattern: '**/*.md',
        strictExt: true,
        ignoreFilePattern: ['errors', 'document_structure'],
        ignoreHashPattern: ['actions-2', 'primary-key-2'],
        exitLevel: 'warn',
      },
    ],
    ['vuepress-plugin-container', { type: 'note' }],
    [require('./config-path-checker')],
    [require('./custom-markdown-rules')],
    [require('./code-samples')],
    [
      'vuepress-plugin-code-copy',
      {
        color: '#FF5CAA',
        staticIcon: true,
      },
    ],
    [
      'meilisearch',
      {
        hostUrl: '',
        apiKey:
          '',
        indexUid: 'docs',
        placeholder: 'Search as you type…',
        enableDarkMode: 'false', // Default: false
      },
    ],
    [
      'vuepress-plugin-zooming',
      {
        selector: '.theme-default-content img',
        delay: 1000,
        options: {
          bgColor: 'black',
          zIndex: 10000,
        },
      },
    ],
  ],
}

```

**Comment by bidoubiwa** [comment]
The issue seems to be with a DOM selector and not the content of the documents. Are you using a custom theme?

**Comment by rmGFW** [comment]
> The issue seems to be with a DOM selector and not the content of the documents. Are you using a custom theme?

yes , i use this ,   theme: 'default-prefers-color-scheme',

**Comment by bidoubiwa** [comment]
Is your app online? So that I can check your HTML tags

**Comment by rmGFW** [comment]
> Is your app online? So that I can check your HTML tags

i can send the address to u by email

**Comment by bidoubiwa** [comment]
Can you come to the community slack ? On [the docs](https://docs.meilisearch.com/), in the menu `More Meilisearch`, click `slack`. You can find me as charlotte :)

**Comment by bidoubiwa** [comment]
Any update on this?

**Comment by bidoubiwa** [comment]
As per the new policy introduced with the deprecation, we only accept issues raising bugs.
For this reason, I'm closing the issue.
