### ISSUE TITLE
enableDarkMode not working

### ISSUE THREAD

**Issue by rmGFW** [meilisearch/vuepress-plugin-meilisearch#256]
the enableDarkMode not working , if u set it to false , the dark mode is still there

**Comment by bidoubiwa** [comment]
Hey @rmGFW 
I'm not able to reproduce, can you show me your config ?

**Comment by rmGFW** [comment]
> 

pull this repo https://github.com/meilisearch/documentation
and comment enableDarkMode in the .vuepress/config.js or set it to false 
then start the dev server  ( you must try this in the night, ) 
then you can see the search bar is still dark mode
<img width="667" alt="image" src="https://user-images.githubusercontent.com/66858140/188320080-f7d537ab-ae81-4147-982c-275d36f3b26f.png">

**Comment by bidoubiwa** [comment]
Hey @rmGFW ! The darkmode of the meilisearch docs works well for me. Is it possible that you have a browser extension that overrides color schemes ?

**Comment by bidoubiwa** [comment]
Closing this, if it is still a bug feel free to re-open
