### ISSUE TITLE
Meilisearch docs glitches on refreshes 

### ISSUE THREAD

**Issue by brunoocasali** [meilisearch/vuepress-plugin-meilisearch#263]
I think this is a non-intentional behavior, and it would be awesome if we could make it work without this glitch. I believe in slower connections, and the experience is not that good.

https://user-images.githubusercontent.com/4116980/163203388-6bca56fa-f545-4f42-b3c0-20e3a9d9e839.mov

**Comment by ColinFrick** [comment]
I created the PR here #264 and in meilisearch/documentation#1910 

Because documentation uses `(prefers-color-scheme: dark)` the site is already rendered in dark mode, while the search input is in light mode until docs-searchbar.js is initalized, therefor it flashes white.
