### ISSUE TITLE
Footer `Powered by` is at the bottom right instead of bottom left

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/vuepress-plugin-meilisearch#269]
Currently, `Powered by` is at the bottom left of the popup. It should be next to `Meilisearch`. 

<img width="509" alt="Screenshot 2022-10-17 at 13 33 26" src="https://user-images.githubusercontent.com/33010418/196167037-4e003275-d7af-49ab-9538-614bcaec9f6f.png">

**Comment by bhanuloshali1995** [comment]
@bidoubiwa Please assign this to me

**Comment by bidoubiwa** [comment]
Thanks for your interest in this project 🔥 You are definitely more than welcome to open a PR for this!

We prefer not assigning people to our issues because sometimes people ask to be assigned and never come back, which discourages the real volunteers contributors from opening a PR to fix this issue.
We will accept and merge the first PR that fixes correctly and well implements the issue following our [contributing guidelines](../blob/main/README.md). 

We are looking forward to reviewing your PR 😊

**Comment by bhanuloshali1995** [comment]
@bidoubiwa I have raised the PR. Please have a look

**Comment by bhanuloshali1995** [comment]
@bidoubiwa Would you please have a look?
