### ISSUE TITLE
How to configure vuepress v2.x config.ts?

### ISSUE THREAD

**Issue by vvfock3r** [meilisearch/vuepress-plugin-meilisearch#293]
My configuration file is config.ts, not config.js. Can you help me

**Comment by bidoubiwa** [comment]
Hey! Unfortunately we are not compatible with vuepress v2 and it is not planned that we will be :(

**Comment by bidoubiwa** [comment]
Closing as it is a duplicate of #175

**Comment by TonyRL** [comment]
> Hey! Unfortunately, we are not compatible with vuepress v2. We are waiting for external contributing to make it compatible.
> 
> See #175

It's not an issue with VuePress v2. VuePress v1 itself supports [TypeScript as Config](https://vuepress.vuejs.org/guide/typescript-as-config.html#overview).

**Comment by JQiue** [comment]
https://github.com/JQiue/vuepress-plugin-meilisearch2/blob/main/README.md#vuepress-plugin-meilisearch2
