### ISSUE TITLE
Incorrect links in README.md for docs

### ISSUE THREAD

**Issue by shivaylamba** [meilisearch/vuepress-plugin-meilisearch#301]
**Description**
Incorrect links in README.md for docs
There are two such links: 
1. https://www.meilisearch.com/docs/reference/under_the_hood/typotolerance
2. https://www.meilisearch.com/docs/create/how_to/search_bar_for_docs

**Expected behavior**
Docs link mentioned in the README should point to the correct URL. 

**Current behavior**
After docs migrated, they no longer point to the correct URL

**Screenshots or Logs**
If applicable, add screenshots or logs to help explain your problem.
<img width="1439" alt="image" src="https://github.com/meilisearch/vuepress-plugin-meilisearch/assets/19529592/99bb365f-cea9-4d50-9018-88db632140f6">

**Comment by bidoubiwa** [comment]
Thanks for raising this 🙏
