### ISSUE TITLE
Include a point in README about Node version comptability 

### ISSUE THREAD

**Issue by shivaylamba** [meilisearch/vuepress-plugin-meilisearch#303]
Right now the playground only supports Node version 16 or below. We should include this in the README to make people aware of what Node version is supported.

**Comment by bidoubiwa** [comment]
Defintely something I should have mentioned. It should be updated as well to work with node 18.

**Comment by bidoubiwa** [comment]
As per the new policy introduced with the deprecation, we only accept issues raising bugs.
For this reason, I'm closing the issue.
